spring.application.name=spotify-project

# Spotify API base url
spotify.api.base-url=https://api.spotify.com/v1

spotify.accounts.base-url=https://accounts.spotify.com
spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
